CREATE TABLE IF NOT EXISTS INVENTORY(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  PRICE NUMERIC,
  QUANTITY NUMERIC,
  CATEGORY TEXT,
  DELETED INTEGER DEFAULT 0 CHECK (DELETED IN (0, 1)),
  CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INVENTORY_HISTORY(
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  EVENT_TYPE TEXT CHECK (EVENT_TYPE IN ('CREATED', 'UPDATED', 'DELETED')),
  INVENTORY_NAME TEXT,
  ID_INVENTORY INTEGER,
  DATE_EVENT DATETIME DEFAULT CURRENT_TIMESTAMP QUANTITY NUMERIC,
  PRICE NUMERIC,
  FOREIGN KEY(ID_INVENTORY) REFERENCES INVENTORY(ID)
);
